### ISSUE TITLE
Change the way the options are customized

### ISSUE THREAD

**Issue by ricvillagrana** [ricvillagrana/capybara_watcher#12]
The docs suggest to use this way to configure CapybaraWatcher options:
```ruby
CapybaraWatcher.configure do |options|
  options.timeout = 1
end
```

But it works only with this way:
```ruby
CapybaraWatcher.configure do |options|
  options[:timeout] = 1
end
```

**Comment by skrishna243** [comment]
so you want to update that change in docs right?

**Comment by ricvillagrana** [comment]
I'd rather having a code update, it would look cleaner.
